// <auto-generated />
using System;
using CzechCurrency.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CzechCurrency.Data.Migrations.Migrations
{
    [DbContext(typeof(CzechCurrencyDbContext))]
    partial class CzechCurrencyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CzechCurrency.Entities.Currency", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnName("code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Amount")
                        .HasColumnName("amount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .HasColumnName("number")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("currencies");

                    b.HasData(
                        new
                        {
                            Code = "AUD",
                            Amount = 1,
                            Name = "Австралийский доллар",
                            Number = "036"
                        },
                        new
                        {
                            Code = "BGN",
                            Amount = 1,
                            Name = "Болгарский лев",
                            Number = "975"
                        },
                        new
                        {
                            Code = "BRL",
                            Amount = 1,
                            Name = "Бразильский реал",
                            Number = "840"
                        },
                        new
                        {
                            Code = "CHF",
                            Amount = 1,
                            Name = "Швейцарский франк",
                            Number = "756"
                        },
                        new
                        {
                            Code = "CNY",
                            Amount = 1,
                            Name = "Юань",
                            Number = "156"
                        },
                        new
                        {
                            Code = "DKK",
                            Amount = 1,
                            Name = "Датская крона",
                            Number = "208"
                        },
                        new
                        {
                            Code = "EUR",
                            Amount = 1,
                            Name = "Евро",
                            Number = "978"
                        },
                        new
                        {
                            Code = "GBP",
                            Amount = 1,
                            Name = "Фунт стерлингов",
                            Number = "826"
                        },
                        new
                        {
                            Code = "HKD",
                            Amount = 1,
                            Name = "Гонконгский доллар",
                            Number = "344"
                        },
                        new
                        {
                            Code = "HRK",
                            Amount = 1,
                            Name = "Хорватская куна",
                            Number = "191"
                        },
                        new
                        {
                            Code = "HUF",
                            Amount = 100,
                            Name = "Форинт",
                            Number = "348"
                        },
                        new
                        {
                            Code = "IDR",
                            Amount = 1000,
                            Name = "Рупия",
                            Number = "360"
                        },
                        new
                        {
                            Code = "ILS",
                            Amount = 1,
                            Name = "Новый израильский шекель",
                            Number = "376"
                        },
                        new
                        {
                            Code = "ISK",
                            Amount = 100,
                            Name = "Исландская крона",
                            Number = "352"
                        },
                        new
                        {
                            Code = "JPY",
                            Amount = 100,
                            Name = "Иена",
                            Number = "392"
                        },
                        new
                        {
                            Code = "KRW",
                            Amount = 100,
                            Name = "Вона",
                            Number = "410"
                        },
                        new
                        {
                            Code = "MXN",
                            Amount = 1,
                            Name = "Мексиканское песо",
                            Number = "979"
                        },
                        new
                        {
                            Code = "MYR",
                            Amount = 1,
                            Name = "Малайзийский ринггит",
                            Number = "458"
                        },
                        new
                        {
                            Code = "NOK",
                            Amount = 1,
                            Name = "Норвежская крона",
                            Number = "578"
                        },
                        new
                        {
                            Code = "NZD",
                            Amount = 1,
                            Name = "Новозеландский доллар",
                            Number = "554"
                        },
                        new
                        {
                            Code = "PHP",
                            Amount = 100,
                            Name = "Филиппинское песо",
                            Number = "608"
                        },
                        new
                        {
                            Code = "PLN",
                            Amount = 1,
                            Name = "Злотый",
                            Number = "985"
                        },
                        new
                        {
                            Code = "RON",
                            Amount = 1,
                            Name = "Новый румынский лей",
                            Number = "946"
                        },
                        new
                        {
                            Code = "RUB",
                            Amount = 100,
                            Name = "Российский рубль",
                            Number = "643"
                        },
                        new
                        {
                            Code = "SEK",
                            Amount = 1,
                            Name = "Шведская крона",
                            Number = "752"
                        },
                        new
                        {
                            Code = "SGD",
                            Amount = 1,
                            Name = "Сингапурский доллар",
                            Number = "702"
                        },
                        new
                        {
                            Code = "THB",
                            Amount = 100,
                            Name = "Тайский Бат",
                            Number = "764"
                        },
                        new
                        {
                            Code = "TRY",
                            Amount = 1,
                            Name = "Турецкая лира",
                            Number = "949"
                        },
                        new
                        {
                            Code = "USD",
                            Amount = 1,
                            Name = "Доллар США",
                            Number = "840"
                        },
                        new
                        {
                            Code = "XDR",
                            Amount = 1,
                            Name = "СДР (специальные права заимствования)",
                            Number = "960"
                        },
                        new
                        {
                            Code = "ZAR",
                            Amount = 1,
                            Name = "Рэнд",
                            Number = "710"
                        },
                        new
                        {
                            Code = "CAD",
                            Amount = 1,
                            Name = "Канадский доллар",
                            Number = "124"
                        },
                        new
                        {
                            Code = "INR",
                            Amount = 100,
                            Name = "Индийская рупия",
                            Number = "356"
                        });
                });

            modelBuilder.Entity("CzechCurrency.Entities.ExchangeRate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CurrencyCode")
                        .HasColumnName("code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Date")
                        .HasColumnName("date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Value")
                        .HasColumnName("value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyCode");

                    b.ToTable("exchange_rates");
                });

            modelBuilder.Entity("CzechCurrency.Entities.ExchangeRate", b =>
                {
                    b.HasOne("CzechCurrency.Entities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyCode");
                });
#pragma warning restore 612, 618
        }
    }
}
